Repository vadimkorr/svelte-carousel, pull requests merged in 2022-05, with the labels that each got.

#107 #84 Validate autoplay duration value, add marquee demo
  src/docs/Carousel.svx
  src/utils/ProgressManager.js
Labels: bug, enhancement

#103 Accessibility : Add keyboard control using html buttons
  src/components/Arrow/Arrow.svelte
  src/components/Dot/Dot.svelte
Labels: enhancement

#109 #94 Fix dispatching pageChange event
  src/components/Carousel/Carousel.svelte
Labels: bug
